apiVersion: batch/v1
kind: CronJob
metadata:
  name: busybox-cron
spec:
  schedule: "*/1 * * * *"   # every minute
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: busybox
              image: busybox:1.36
              command: ["/bin/sh", "-c"]
              env:
                - name: MESSAGE
                  value: "Hello from BusyBox Cron"
              args:
                - 'echo "$(date) - $MESSAGE"'
